version: "3.7"
services:
  default-web:
    container_name: default-web
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - my-networks
    ports:
      - 8000:80
    restart: always

networks:
  my-networks:
    driver: bridge
    name: my-networks
    external: true
